### ISSUE TITLE
Cannot start the container

### ISSUE THREAD

**Issue by thamathar** [goofball222/factorio#32]
Hi
Don't know wha tis the problem, did the clone, changed the docker-compose.yml to what I needed and the just used the command
docker compose up
It did get all that I needed but now I get this error when trying to start, don't know what is wrong here

`standard_init_linux.go:219: exec user process caused: no such file or directory`

This is my docker-compose file.

```
version: '2'
services:
  factorio:
    # image: factoriotools/factorio
    # network_mode: host
    build:
      context: .
      args:
      # Check buildinfo.json for supported versions and SHAs
      # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
      - VERSION=latest
      - SHA256=24bd61cc3aafe2041eb12b91e4f49d784ff6e36083e365d1e6320a34b636bda7
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ./factorio-files:/factorio
    environment:
      - PUID=1000
      - PGID=1000
      - UPDATE_MODS_ON_START=true
      - USERNAME=*********
      - TOKEN=*******
      - PORT=34198
```
